export const atsBondAbi = [
  { type: "function", name: "name", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { type: "function", name: "symbol", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getHeldAmountFor",
    stateMutability: "view",
    inputs: [{ name: "tokenHolder", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  { type: "function", name: "getNominalValue", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  {
    type: "function",
    name: "getNominalValueDecimals",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint8" }],
  },
  {
    type: "function",
    name: "getNominalValueCurrency",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "bytes3" }],
  },
  { type: "function", name: "getMaturityDate", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "getCouponCount", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  {
    type: "function",
    name: "getCoupon",
    stateMutability: "view",
    inputs: [{ name: "couponId", type: "uint256" }],
    outputs: [
      {
        name: "registeredCoupon",
        type: "tuple",
        components: [
          {
            name: "coupon",
            type: "tuple",
            components: [
              { name: "recordDate", type: "uint256" },
              { name: "executionDate", type: "uint256" },
              { name: "startDate", type: "uint256" },
              { name: "endDate", type: "uint256" },
              { name: "fixingDate", type: "uint256" },
              { name: "rate", type: "uint256" },
              { name: "rateDecimals", type: "uint8" },
              { name: "rateStatus", type: "uint8" },
            ],
          },
          { name: "snapshotId", type: "uint256" },
        ],
      },
      { name: "isDisabled", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "isInControlList",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "getKycStatusFor",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ type: "uint8" }],
  },
  {
    type: "function",
    name: "canTransferByPartition",
    stateMutability: "view",
    inputs: [
      { name: "from", type: "address" },
      { name: "to", type: "address" },
      { name: "partition", type: "bytes32" },
      { name: "value", type: "uint256" },
      { name: "data", type: "bytes" },
      { name: "operatorData", type: "bytes" },
    ],
    outputs: [{ type: "bool" }, { type: "bytes1" }, { type: "bytes32" }],
  },
  {
    type: "function",
    name: "createHoldByPartition",
    stateMutability: "nonpayable",
    inputs: [
      { name: "partition", type: "bytes32" },
      {
        name: "hold",
        type: "tuple",
        components: [
          { name: "amount", type: "uint256" },
          { name: "expirationTimestamp", type: "uint256" },
          { name: "escrow", type: "address" },
          { name: "to", type: "address" },
          { name: "data", type: "bytes" },
        ],
      },
    ],
    outputs: [{ type: "bool" }, { type: "uint256" }],
  },
  {
    type: "event",
    name: "HeldByPartition",
    inputs: [
      { name: "operator", type: "address", indexed: true },
      { name: "tokenHolder", type: "address", indexed: true },
      { name: "partition", type: "bytes32", indexed: false },
      { name: "holdId", type: "uint256", indexed: false },
      {
        name: "hold",
        type: "tuple",
        indexed: false,
        components: [
          { name: "amount", type: "uint256" },
          { name: "expirationTimestamp", type: "uint256" },
          { name: "escrow", type: "address" },
          { name: "to", type: "address" },
          { name: "data", type: "bytes" },
        ],
      },
      { name: "operatorData", type: "bytes", indexed: false },
    ],
  },
] as const;

export const exitAuctionAbi = [
  {
    type: "function",
    name: "createAuction",
    stateMutability: "nonpayable",
    inputs: [
      { name: "token", type: "address" },
      { name: "partition", type: "bytes32" },
      { name: "holdId", type: "uint256" },
      { name: "amount", type: "uint256" },
      { name: "deadline", type: "uint64" },
      { name: "reserveCommitment", type: "bytes32" },
    ],
    outputs: [
      { name: "id", type: "uint256" },
      { name: "ref", type: "bytes32" },
    ],
  },
  {
    type: "event",
    name: "AuctionCreated",
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "ref", type: "bytes32", indexed: true },
      { name: "seller", type: "address", indexed: true },
      { name: "token", type: "address", indexed: false },
      { name: "partition", type: "bytes32", indexed: false },
      { name: "holdId", type: "uint256", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
      { name: "deadline", type: "uint64", indexed: false },
      { name: "reserveCommitment", type: "bytes32", indexed: false },
    ],
  },
  { type: "error", name: "NotOperator", inputs: [] },
  { type: "error", name: "NotSeller", inputs: [] },
  { type: "error", name: "BadStatus", inputs: [{ name: "have", type: "uint8" }] },
  { type: "error", name: "DeadlineTooSoon", inputs: [] },
  { type: "error", name: "HoldNotForThisEscrow", inputs: [] },
  { type: "error", name: "HoldHasFixedDestination", inputs: [] },
  { type: "error", name: "HoldAmountMismatch", inputs: [] },
  {
    type: "error",
    name: "HoldExpiresTooEarly",
    inputs: [
      { name: "expiration", type: "uint256" },
      { name: "needed", type: "uint256" },
    ],
  },
  { type: "error", name: "AlreadyListed", inputs: [] },
  { type: "error", name: "BeforeDeadline", inputs: [] },
  { type: "error", name: "AfterDeadline", inputs: [] },
  { type: "error", name: "ZeroAddress", inputs: [] },
] as const;

export const bidEscrowAbi = [
  {
    type: "function",
    name: "placeBid",
    stateMutability: "nonpayable",
    inputs: [
      { name: "ref", type: "bytes32" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [{ name: "ref", type: "bytes32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "refundable",
    stateMutability: "view",
    inputs: [
      { name: "ref", type: "bytes32" },
      { name: "who", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getBids",
    stateMutability: "view",
    inputs: [{ name: "ref", type: "bytes32" }],
    outputs: [
      { name: "bidders", type: "address[]" },
      { name: "amounts", type: "uint256[]" },
    ],
  },
  {
    type: "function",
    name: "getAuction",
    stateMutability: "view",
    inputs: [{ name: "ref", type: "bytes32" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "seller", type: "address" },
          { name: "deadline", type: "uint64" },
          { name: "awardedAt", type: "uint64" },
          { name: "reserveCommitment", type: "bytes32" },
          { name: "status", type: "uint8" },
          { name: "winner", type: "address" },
          { name: "clearingPrice", type: "uint256" },
          { name: "source", type: "uint8" },
          { name: "hederaTxHash", type: "bytes32" },
          { name: "hederaAuctionId", type: "uint256" },
          { name: "totalEscrowed", type: "uint256" },
        ],
      },
    ],
  },
  {
    type: "event",
    name: "BidPlaced",
    inputs: [
      { name: "ref", type: "bytes32", indexed: true },
      { name: "bidder", type: "address", indexed: true },
      { name: "added", type: "uint256", indexed: false },
      { name: "total", type: "uint256", indexed: false },
    ],
  },
  { type: "error", name: "NotOperator", inputs: [] },
  { type: "error", name: "BadStatus", inputs: [{ name: "have", type: "uint8" }] },
  { type: "error", name: "BeforeDeadline", inputs: [] },
  { type: "error", name: "AfterDeadline", inputs: [] },
  { type: "error", name: "UnknownRef", inputs: [] },
  { type: "error", name: "CommitmentMismatch", inputs: [] },
  { type: "error", name: "InsufficientBid", inputs: [] },
  { type: "error", name: "NothingToWithdraw", inputs: [] },
  { type: "error", name: "TooEarly", inputs: [] },
  { type: "error", name: "ZeroAmount", inputs: [] },
  { type: "error", name: "ZeroAddress", inputs: [] },
] as const;

export const erc20Abi = [
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "allowance",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
] as const;

export const atsErrorAbi = [
  { type: "error", name: "AccountIsBlocked", inputs: [] },
  { type: "error", name: "InvalidKycStatus", inputs: [] },
  { type: "error", name: "AddressNotVerified", inputs: [] },
  { type: "error", name: "ComplianceNotAllowed", inputs: [] },
  { type: "error", name: "IsPaused", inputs: [] },
] as const;
